trigger: 
 - main
pool: dev-infra-pool


stages: 
 - stage: TERRAFORM_INSTALL
   displayName: TERRAFORM_INSTALL
   jobs:
     - job: TERRAFORM_INSTALL
       steps: 

       - task: TerraformInstaller@1
         inputs:
           terraformVersion: 'latest'

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'kashi-dev-app'
           backendAzureRmStorageAccountName: 'statefile89234'
           backendAzureRmContainerName: 'statefile'
           backendAzureRmKey: 'prod.terraform.tfstate'


 - stage: TERRAFORM_VALIDATE
   displayName: TERRAFORM_VALIDATE
   jobs:
     - job: TERRAFORM_VALIDATE
       steps: 

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'kashi-dev-app'
           backendAzureRmStorageAccountName: 'statefile89234'
           backendAzureRmContainerName: 'statefile'
           backendAzureRmKey: 'prod.terraform.tfvars'

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'validate'

 - stage: SCANINIG_TOOL
   displayName: SCANINIG_TOOL
   jobs:
     - job: SCANINIG_TOOL
       steps: 

       - task: tfsec@1
         inputs:
           version: 'v1.26.0'


 - stage: MANUAL_VALIDATION
   displayName: MANUAL_VALIDATION
   jobs:
     - job: MANUAL_VALIDATION
       pool: server
       steps: 

       - task: ManualValidation@1
         inputs:
           notifyUsers: 'shashisingh223344@gmail.com'
           approvers: 'shashisingh223344@gmail.com'
           instructions: 'please check and approve'

 - stage: TERRAFORM_PLAN
   displayName: TERRAFORM_PLAN
   jobs:
     - job: TERRAFORM_PLAN
       steps: 

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           backendServiceArm: 'kashi-dev-app'
           backendAzureRmStorageAccountName: 'statefile89234'
           backendAzureRmContainerName: 'statefile'
           backendAzureRmKey: 'prod.terraform.tfvars'

       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'plan'
           environmentServiceNameAzureRM: 'kashi-dev-app'